const AVATAR_COUNT = 0;
const SESSION_EXPIRES_IN = 86400;
const REFRESH_SESSION_EXPIRES_IN = 604800;

const PRODUCE_STATUS = {
    AVAILABLE: 0,
    REMOVED: 1
}

module.exports = { AVATAR_COUNT, SESSION_EXPIRES_IN, REFRESH_SESSION_EXPIRES_IN, PRODUCE_STATUS };